Add interest
ILUVUS/iluvus-backend-api-JIA-3317 pull request #53
Opened 2024-03-31 05:57 UTC by doan1212

Save a list of interests after user select

2024-03-31 21:03 UTC, thuanvoit requested changes
Ready to merge Wait for #52

2024-03-31 21:11 UTC, nilrelyt approved these changes
Great work!

2024-03-31 21:26 UTC, binayatimsina approved these changes
Great work Doan

2024-04-01 02:08 UTC, thuanvoit approved these changes
Good job!

2024-04-01 05:13 UTC, merged